version: '3.2'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"